### PR TITLE
Fix scope for artist link page

### LINKED ISSUE #537: Artist link search does not preserve search query
1. Go to artist link requests
2. Search for something
3. Go to page 2
4. Observe that the search query is reset to nothing

### PR DESCRIPTION
**Pull request by mdashlw**
### Before you begin

- I understand my contributions may be rejected for any reason
- I understand my contributions are for the benefit of Derpibooru and/or the Philomena software
- I understand my contributions are licensed under the GNU AGPLv3

* [x] I understand all of the above

---

fixes #537

### CODE REVIEW

File: lib/philomena_web/views/admin/artist_link_view.ex [hunk 1]
```diff
@@ -21,10 +21,17 @@ defmodule PhilomenaWeb.Admin.ArtistLinkView do
...
+    []
+    |> scope(conn, "lq", :lq)
+    |> scope(conn, "all", :all)
+  end
+
+  defp scope(list, conn, key, key_atom) do
+    case conn.params[key] do
+      nil -> list
+      "" -> list
+      val -> [{key_atom, val} | list]
```
Comment (Meow) [inline lib/philomena_web/views/admin/artist_link_view.ex:34]: Technically not the same behavior as previously. Your code sets the value to `conn.params[key]`, the old code set it to `true`.

Comment (mdashlw) [reply lib/philomena_web/views/admin/artist_link_view.ex:34]: It doesn't matter. The controller only checks for presence, not "true"

**Comment by MareStare** [comment]
# QA

Now when you click on the next page of artist links search results, the query is preserved in query params
image
