### PR TITLE
Fix autoclosing reports overriding admin_id

### LINKED ISSUE #513: close_report_query shouldn't close already closed reports
https://github.com/philomena-dev/philomena/blob/46420fe3a16e06b216829263c036a9375b7db412/lib/philomena/reports.ex#L116

### PR DESCRIPTION
**Pull request by mdashlw**
### Before you begin

- I understand my contributions may be rejected for any reason
- I understand my contributions are for the benefit of Derpibooru and/or the Philomena software
- I understand my contributions are licensed under the GNU AGPLv3

* [x] I understand all of the above

---

fixes #513

### CODE REVIEW

File: lib/philomena/reports.ex [hunk 1]
```diff
@@ -78,21 +78,21 @@ defmodule Philomena.Reports do
       {:error, %Ecto.Changeset{}}
 
   """
-  def create_report({reportable_type, reportable_id} = _type_and_id, attribution, attrs \\ %{}) do
```
Comment (liamwhite) [inline lib/philomena/reports.ex:81]: `_type_and_id` is for the generated documentation, and changes the function signature if it's removed from `create_report(type_and_id, attribution, attrs \\ %{})` to `create_report(arg_1, attribution, attrs \\ %{})`

Comment (MareStare) [reply lib/philomena/reports.ex]: Is the generated documentation used by anyone? I believe all who are interested in this code read it in their ide including the comments

Comment (liamwhite) [reply lib/philomena/reports.ex]: I put some effort into creating it a while ago and documenting many interfaces using the ExDoc format, it'd be nice if it could be used in the future

**Comment by MareStare** [comment]
Manually tested. Before this change the reports "closed by" was changing for already closed reports when the image is hidden.

After this change the "closed by" stays the same
